// <auto-generated />
using Ejercicio_Sesión_1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ejercicio_Sesión_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220526171053_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.4.22229.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ejercicio_Sesión_1.Entidades.Editorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Editoriales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Campbell"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Timunmas"
                        });
                });

            modelBuilder.Entity("Ejercicio_Sesión_1.Entidades.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EditorialId")
                        .HasColumnType("int");

                    b.Property<int>("Paginas")
                        .HasMaxLength(10000)
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("EditorialId");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EditorialId = 1,
                            Paginas = 300,
                            Titulo = "Warhammer"
                        },
                        new
                        {
                            Id = 2,
                            EditorialId = 2,
                            Paginas = 500,
                            Titulo = "Sherlock"
                        },
                        new
                        {
                            Id = 3,
                            EditorialId = 2,
                            Paginas = 340,
                            Titulo = "DragonLance"
                        },
                        new
                        {
                            Id = 4,
                            EditorialId = 1,
                            Paginas = 250,
                            Titulo = "Pesadillas"
                        },
                        new
                        {
                            Id = 5,
                            EditorialId = 1,
                            Paginas = 120,
                            Titulo = "Wally"
                        },
                        new
                        {
                            Id = 6,
                            EditorialId = 1,
                            Paginas = 200,
                            Titulo = "NameWind"
                        },
                        new
                        {
                            Id = 7,
                            EditorialId = 2,
                            Paginas = 340,
                            Titulo = "ManSapience"
                        },
                        new
                        {
                            Id = 8,
                            EditorialId = 1,
                            Paginas = 400,
                            Titulo = "LunaWolfes"
                        },
                        new
                        {
                            Id = 9,
                            EditorialId = 1,
                            Paginas = 450,
                            Titulo = "ImperialFists"
                        },
                        new
                        {
                            Id = 10,
                            EditorialId = 1,
                            Paginas = 333,
                            Titulo = "SpaceWolfes"
                        });
                });

            modelBuilder.Entity("Ejercicio_Sesión_1.Entidades.Libro", b =>
                {
                    b.HasOne("Ejercicio_Sesión_1.Entidades.Editorial", "Editorial")
                        .WithMany("Libros")
                        .HasForeignKey("EditorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editorial");
                });

            modelBuilder.Entity("Ejercicio_Sesión_1.Entidades.Editorial", b =>
                {
                    b.Navigation("Libros");
                });
#pragma warning restore 612, 618
        }
    }
}
